//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cIncidenciaProblema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cIncidenciaProblema()
        {
            this.reporteTiendaIncidencia = new HashSet<reporteTiendaIncidencia>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int idEstado { get; set; }
    
        public virtual cEstado cEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTiendaIncidencia> reporteTiendaIncidencia { get; set; }
    }
}
