//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.producto = new HashSet<producto>();
            this.ruta = new HashSet<ruta>();
            this.segmentos = new HashSet<segmentos>();
            this.usuarioCliente = new HashSet<usuarioCliente>();
            this.estatusPorCliente = new HashSet<estatusPorCliente>();
        }
    
        public int id { get; set; }
        public string razonSocial { get; set; }
        public string domicilio { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> iddEstado { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
    
        public virtual cEstado cEstado { get; set; }
        public virtual destado destado { get; set; }
        public virtual cmunicipio cmunicipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruta> ruta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<segmentos> segmentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioCliente> usuarioCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estatusPorCliente> estatusPorCliente { get; set; }
    }
}
