//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estatusPorCliente
    {
        public int id { get; set; }
        public Nullable<int> rangoInferior { get; set; }
        public Nullable<int> rangoSuperior { get; set; }
        public Nullable<int> idEstatus { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual inventarioEstatus inventarioEstatus { get; set; }
    }
}
