//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estatusPorCliente
    {
        public int id { get; set; }
        public Nullable<int> rangoInferior { get; set; }
        public Nullable<int> rangoSuperior { get; set; }
        public Nullable<int> idEstatus { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual inventarioEstatus inventarioEstatus { get; set; }
    }
}
