//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    
    public partial class fnReporteTiempoEfectivo_Result1
    {
        public Nullable<int> idUsuarioPromotor { get; set; }
        public string nombre { get; set; }
        public Nullable<int> numSemana { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> lunes { get; set; }
        public Nullable<int> martes { get; set; }
        public Nullable<int> miercoles { get; set; }
        public Nullable<int> jueves { get; set; }
        public Nullable<int> viernes { get; set; }
        public Nullable<int> sabado { get; set; }
        public Nullable<int> total { get; set; }
    }
}
