//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    
    public partial class fnReporteTiempoEfectivo_Result2
    {
        public Nullable<int> idUsuarioPromotor { get; set; }
        public string nombre { get; set; }
        public Nullable<int> numSemana { get; set; }
        public Nullable<int> ano { get; set; }
        public string lunes { get; set; }
        public int martes { get; set; }
        public int miercoles { get; set; }
        public int jueves { get; set; }
        public int viernes { get; set; }
        public int sabado { get; set; }
        public int total { get; set; }
    }
}
