//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IntegramsaUltimateEntities : DbContext
    {
        public IntegramsaUltimateEntities()
            : base("name=IntegramsaUltimateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cAccionesRecomendaciones> cAccionesRecomendaciones { get; set; }
        public virtual DbSet<cadena> cadena { get; set; }
        public virtual DbSet<cClouster> cClouster { get; set; }
        public virtual DbSet<cDiaSemana> cDiaSemana { get; set; }
        public virtual DbSet<cEstado> cEstado { get; set; }
        public virtual DbSet<cEstadoRuta> cEstadoRuta { get; set; }
        public virtual DbSet<cFactorVisita> cFactorVisita { get; set; }
        public virtual DbSet<cFotoProposito> cFotoProposito { get; set; }
        public virtual DbSet<cGiroComercial> cGiroComercial { get; set; }
        public virtual DbSet<cIncidenciaProblema> cIncidenciaProblema { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cmunicipio> cmunicipio { get; set; }
        public virtual DbSet<cPerfilRuta> cPerfilRuta { get; set; }
        public virtual DbSet<cPlaza> cPlaza { get; set; }
        public virtual DbSet<cTipoAccionRecomendacion> cTipoAccionRecomendacion { get; set; }
        public virtual DbSet<cTiposExhibicion> cTiposExhibicion { get; set; }
        public virtual DbSet<cTipoUsuario> cTipoUsuario { get; set; }
        public virtual DbSet<cTurnoRuta> cTurnoRuta { get; set; }
        public virtual DbSet<cZona> cZona { get; set; }
        public virtual DbSet<destado> destado { get; set; }
        public virtual DbSet<formatoProducto> formatoProducto { get; set; }
        public virtual DbSet<formatoTienda> formatoTienda { get; set; }
        public virtual DbSet<logError> logError { get; set; }
        public virtual DbSet<logErrorMobile> logErrorMobile { get; set; }
        public virtual DbSet<logWebService> logWebService { get; set; }
        public virtual DbSet<participacion> participacion { get; set; }
        public virtual DbSet<PlazaMunicipio> PlazaMunicipio { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<reporteIntinerarioPromotor> reporteIntinerarioPromotor { get; set; }
        public virtual DbSet<reporteTienda> reporteTienda { get; set; }
        public virtual DbSet<reporteTiendaActividadesPropias> reporteTiendaActividadesPropias { get; set; }
        public virtual DbSet<reporteTiendaDetalleCompetencia> reporteTiendaDetalleCompetencia { get; set; }
        public virtual DbSet<reporteTiendaFoto> reporteTiendaFoto { get; set; }
        public virtual DbSet<reporteTiendaIncidencia> reporteTiendaIncidencia { get; set; }
        public virtual DbSet<ReporteTiendaSegmento> ReporteTiendaSegmento { get; set; }
        public virtual DbSet<ruta> ruta { get; set; }
        public virtual DbSet<rutaIntinerario> rutaIntinerario { get; set; }
        public virtual DbSet<rutaTienda> rutaTienda { get; set; }
        public virtual DbSet<segmentoProductos> segmentoProductos { get; set; }
        public virtual DbSet<segmentos> segmentos { get; set; }
        public virtual DbSet<tienda> tienda { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuarioCliente> usuarioCliente { get; set; }
        public virtual DbSet<ZonaEstado> ZonaEstado { get; set; }
        public virtual DbSet<reporteTiendaFrentes> reporteTiendaFrentes { get; set; }
        public virtual DbSet<vwPlazaMunicipio> vwPlazaMunicipio { get; set; }
        public virtual DbSet<vwReporteAsistenciaFechaEspecifica> vwReporteAsistenciaFechaEspecifica { get; set; }
        public virtual DbSet<vwReporteIntinerarioPromotorPlaza> vwReporteIntinerarioPromotorPlaza { get; set; }
        public virtual DbSet<vwreporteTienda> vwreporteTienda { get; set; }
        public virtual DbSet<vwreporteTiendaCobertura> vwreporteTiendaCobertura { get; set; }
        public virtual DbSet<vwRutaIntinerario> vwRutaIntinerario { get; set; }
        public virtual DbSet<vwRutaIntinerarioSinEnviarse> vwRutaIntinerarioSinEnviarse { get; set; }
        public virtual DbSet<vwReporteFotos> vwReporteFotos { get; set; }
        public virtual DbSet<inventarioCriterios> inventarioCriterios { get; set; }
        public virtual DbSet<inventarioCriteriosRes> inventarioCriteriosRes { get; set; }
        public virtual DbSet<vwIDsReporteTienda> vwIDsReporteTienda { get; set; }
        public virtual DbSet<inventarios> inventarios { get; set; }
        public virtual DbSet<vwInventario> vwInventario { get; set; }
        public virtual DbSet<estatusPorCliente> estatusPorCliente { get; set; }
        public virtual DbSet<inventarioEstatus> inventarioEstatus { get; set; }
        public virtual DbSet<vwInventarioMainReport> vwInventarioMainReport { get; set; }
        public virtual DbSet<vwReporteFotosUrl> vwReporteFotosUrl { get; set; }
        public virtual DbSet<vwreporteEfectivadPrincipal> vwreporteEfectivadPrincipal { get; set; }
        public virtual DbSet<vwclienteCoordinador> vwclienteCoordinador { get; set; }
        public virtual DbSet<vwcoordinador> vwcoordinador { get; set; }
        public virtual DbSet<vwta> vwta { get; set; }
    
        [DbFunction("IntegramsaUltimateEntities", "fnctCurrentWeek")]
        public virtual IQueryable<fnctCurrentWeek_Result> fnctCurrentWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnctCurrentWeek_Result>("[IntegramsaUltimateEntities].[fnctCurrentWeek]()");
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnObtieneRutaIntinerarioSinEnviarse")]
        public virtual IQueryable<fnObtieneRutaIntinerarioSinEnviarse_Result> fnObtieneRutaIntinerarioSinEnviarse(Nullable<int> numSemana, Nullable<int> idUsuario)
        {
            var numSemanaParameter = numSemana.HasValue ?
                new ObjectParameter("numSemana", numSemana) :
                new ObjectParameter("numSemana", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnObtieneRutaIntinerarioSinEnviarse_Result>("[IntegramsaUltimateEntities].[fnObtieneRutaIntinerarioSinEnviarse](@numSemana, @idUsuario)", numSemanaParameter, idUsuarioParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistenciaCobertura")]
        public virtual IQueryable<fnReporteAsistenciaCobertura_Result> fnReporteAsistenciaCobertura(Nullable<int> numSemana, Nullable<int> idUsuarioPromotor, Nullable<int> ano)
        {
            var numSemanaParameter = numSemana.HasValue ?
                new ObjectParameter("numSemana", numSemana) :
                new ObjectParameter("numSemana", typeof(int));
    
            var idUsuarioPromotorParameter = idUsuarioPromotor.HasValue ?
                new ObjectParameter("idUsuarioPromotor", idUsuarioPromotor) :
                new ObjectParameter("idUsuarioPromotor", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistenciaCobertura_Result>("[IntegramsaUltimateEntities].[fnReporteAsistenciaCobertura](@numSemana, @idUsuarioPromotor, @ano)", numSemanaParameter, idUsuarioPromotorParameter, anoParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistenciaFechaEspecifica")]
        public virtual IQueryable<fnReporteAsistenciaFechaEspecifica_Result> fnReporteAsistenciaFechaEspecifica(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> idCliente)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistenciaFechaEspecifica_Result>("[IntegramsaUltimateEntities].[fnReporteAsistenciaFechaEspecifica](@fechaInicio, @fechaFin, @idCliente)", fechaInicioParameter, fechaFinParameter, idClienteParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistenciaFechaEspecificaPromedio")]
        public virtual IQueryable<fnReporteAsistenciaFechaEspecificaPromedio_Result> fnReporteAsistenciaFechaEspecificaPromedio(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> idCliente)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistenciaFechaEspecificaPromedio_Result>("[IntegramsaUltimateEntities].[fnReporteAsistenciaFechaEspecificaPromedio](@fechaInicio, @fechaFin, @idCliente)", fechaInicioParameter, fechaFinParameter, idClienteParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteTiempoEfectivo")]
        public virtual IQueryable<fnReporteTiempoEfectivo_Result> fnReporteTiempoEfectivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteTiempoEfectivo_Result>("[IntegramsaUltimateEntities].[fnReporteTiempoEfectivo]()");
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteTiempoEfectivoByCadena")]
        public virtual IQueryable<fnReporteTiempoEfectivoByCadena_Result> fnReporteTiempoEfectivoByCadena(Nullable<int> idCadena, Nullable<int> numSemana, Nullable<int> ano)
        {
            var idCadenaParameter = idCadena.HasValue ?
                new ObjectParameter("idCadena", idCadena) :
                new ObjectParameter("idCadena", typeof(int));
    
            var numSemanaParameter = numSemana.HasValue ?
                new ObjectParameter("numSemana", numSemana) :
                new ObjectParameter("numSemana", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteTiempoEfectivoByCadena_Result>("[IntegramsaUltimateEntities].[fnReporteTiempoEfectivoByCadena](@idCadena, @numSemana, @ano)", idCadenaParameter, numSemanaParameter, anoParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteTiempoEfectivoDeCadena")]
        public virtual IQueryable<fnReporteTiempoEfectivoDeCadena_Result> fnReporteTiempoEfectivoDeCadena(Nullable<int> idCadena, Nullable<int> numSemana, Nullable<int> ano)
        {
            var idCadenaParameter = idCadena.HasValue ?
                new ObjectParameter("idCadena", idCadena) :
                new ObjectParameter("idCadena", typeof(int));
    
            var numSemanaParameter = numSemana.HasValue ?
                new ObjectParameter("numSemana", numSemana) :
                new ObjectParameter("numSemana", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteTiempoEfectivoDeCadena_Result>("[IntegramsaUltimateEntities].[fnReporteTiempoEfectivoDeCadena](@idCadena, @numSemana, @ano)", idCadenaParameter, numSemanaParameter, anoParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteTiempoEfectivoMuerto")]
        public virtual IQueryable<fnReporteTiempoEfectivoMuerto_Result> fnReporteTiempoEfectivoMuerto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteTiempoEfectivoMuerto_Result>("[IntegramsaUltimateEntities].[fnReporteTiempoEfectivoMuerto]()");
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteTiempoEfectivoPorCadena")]
        public virtual IQueryable<fnReporteTiempoEfectivoPorCadena_Result> fnReporteTiempoEfectivoPorCadena(Nullable<int> idCadena)
        {
            var idCadenaParameter = idCadena.HasValue ?
                new ObjectParameter("idCadena", idCadena) :
                new ObjectParameter("idCadena", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteTiempoEfectivoPorCadena_Result>("[IntegramsaUltimateEntities].[fnReporteTiempoEfectivoPorCadena](@idCadena)", idCadenaParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteTiempoEfectivoPorCadenaXC")]
        public virtual IQueryable<fnReporteTiempoEfectivoPorCadenaXC_Result> fnReporteTiempoEfectivoPorCadenaXC(Nullable<int> idCadena, Nullable<int> numSemana, Nullable<int> ano, Nullable<int> idCliente)
        {
            var idCadenaParameter = idCadena.HasValue ?
                new ObjectParameter("idCadena", idCadena) :
                new ObjectParameter("idCadena", typeof(int));
    
            var numSemanaParameter = numSemana.HasValue ?
                new ObjectParameter("numSemana", numSemana) :
                new ObjectParameter("numSemana", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteTiempoEfectivoPorCadenaXC_Result>("[IntegramsaUltimateEntities].[fnReporteTiempoEfectivoPorCadenaXC](@idCadena, @numSemana, @ano, @idCliente)", idCadenaParameter, numSemanaParameter, anoParameter, idClienteParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnRepTiempoExCadxCliente")]
        public virtual IQueryable<fnRepTiempoExCadxCliente_Result> fnRepTiempoExCadxCliente(Nullable<int> idCadena, Nullable<int> numSemana, Nullable<int> ano, Nullable<int> idCliente)
        {
            var idCadenaParameter = idCadena.HasValue ?
                new ObjectParameter("idCadena", idCadena) :
                new ObjectParameter("idCadena", typeof(int));
    
            var numSemanaParameter = numSemana.HasValue ?
                new ObjectParameter("numSemana", numSemana) :
                new ObjectParameter("numSemana", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnRepTiempoExCadxCliente_Result>("[IntegramsaUltimateEntities].[fnRepTiempoExCadxCliente](@idCadena, @numSemana, @ano, @idCliente)", idCadenaParameter, numSemanaParameter, anoParameter, idClienteParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnRepTiempoTotalCadenas")]
        public virtual IQueryable<fnRepTiempoTotalCadenas_Result> fnRepTiempoTotalCadenas(Nullable<int> idCadena, Nullable<int> numSemana, Nullable<int> ano, Nullable<int> idCliente)
        {
            var idCadenaParameter = idCadena.HasValue ?
                new ObjectParameter("idCadena", idCadena) :
                new ObjectParameter("idCadena", typeof(int));
    
            var numSemanaParameter = numSemana.HasValue ?
                new ObjectParameter("numSemana", numSemana) :
                new ObjectParameter("numSemana", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnRepTiempoTotalCadenas_Result>("[IntegramsaUltimateEntities].[fnRepTiempoTotalCadenas](@idCadena, @numSemana, @ano, @idCliente)", idCadenaParameter, numSemanaParameter, anoParameter, idClienteParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistencia3meses")]
        public virtual IQueryable<fnReporteAsistencia3meses_Result> fnReporteAsistencia3meses(Nullable<int> idCliente, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistencia3meses_Result>("[IntegramsaUltimateEntities].[fnReporteAsistencia3meses](@idCliente, @fechaInicio, @fechaFin)", idClienteParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistenciaNewIni")]
        public virtual IQueryable<fnReporteAsistenciaNewIni_Result> fnReporteAsistenciaNewIni(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistenciaNewIni_Result>("[IntegramsaUltimateEntities].[fnReporteAsistenciaNewIni](@fechaInicio, @fechaFin)", fechaInicioParameter, fechaFinParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistenciaPasados")]
        public virtual IQueryable<fnReporteAsistenciaPasados_Result> fnReporteAsistenciaPasados(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistenciaPasados_Result>("[IntegramsaUltimateEntities].[fnReporteAsistenciaPasados](@fechaInicio, @fechaFin)", fechaInicioParameter, fechaFinParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistenciaPrincipal")]
        public virtual IQueryable<fnReporteAsistenciaPrincipal_Result> fnReporteAsistenciaPrincipal(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistenciaPrincipal_Result>("[IntegramsaUltimateEntities].[fnReporteAsistenciaPrincipal](@fechaInicio, @fechaFin)", fechaInicioParameter, fechaFinParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistenciaNew")]
        public virtual IQueryable<fnReporteAsistenciaNew_Result> fnReporteAsistenciaNew(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistenciaNew_Result>("[IntegramsaUltimateEntities].[fnReporteAsistenciaNew](@fechaInicio, @fechaFin)", fechaInicioParameter, fechaFinParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteEfectividadNew")]
        public virtual IQueryable<fnReporteEfectividadNew_Result> fnReporteEfectividadNew(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteEfectividadNew_Result>("[IntegramsaUltimateEntities].[fnReporteEfectividadNew](@fechaInicio, @fechaFin)", fechaInicioParameter, fechaFinParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteEfectividadNew_copy1")]
        public virtual IQueryable<fnReporteEfectividadNew_copy1_Result> fnReporteEfectividadNew_copy1(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteEfectividadNew_copy1_Result>("[IntegramsaUltimateEntities].[fnReporteEfectividadNew_copy1](@fechaInicio, @fechaFin)", fechaInicioParameter, fechaFinParameter);
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnReporteAsistenciaPas")]
        public virtual IQueryable<fnReporteAsistenciaPas_Result> fnReporteAsistenciaPas(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnReporteAsistenciaPas_Result>("[IntegramsaUltimateEntities].[fnReporteAsistenciaPas](@fechaInicio, @fechaFin)", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<spxGetNewReporteEfectividad_Result> spxGetNewReporteEfectividad(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> id, Nullable<int> idCliente, Nullable<int> filter)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            var filterParameter = filter.HasValue ?
                new ObjectParameter("filter", filter) :
                new ObjectParameter("filter", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spxGetNewReporteEfectividad_Result>("spxGetNewReporteEfectividad", fechaInicioParameter, fechaFinParameter, idParameter, idClienteParameter, filterParameter);
        }
    }
}
