//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimateWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IntegramsaUltimateEntities : DbContext
    {
        public IntegramsaUltimateEntities()
            : base("name=IntegramsaUltimateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cAccionesRecomendaciones> cAccionesRecomendaciones { get; set; }
        public virtual DbSet<cadena> cadena { get; set; }
        public virtual DbSet<cClouster> cClouster { get; set; }
        public virtual DbSet<cDiaSemana> cDiaSemana { get; set; }
        public virtual DbSet<cEstado> cEstado { get; set; }
        public virtual DbSet<cEstadoRuta> cEstadoRuta { get; set; }
        public virtual DbSet<cFactorVisita> cFactorVisita { get; set; }
        public virtual DbSet<cFotoProposito> cFotoProposito { get; set; }
        public virtual DbSet<cGiroComercial> cGiroComercial { get; set; }
        public virtual DbSet<cIncidenciaProblema> cIncidenciaProblema { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cmunicipio> cmunicipio { get; set; }
        public virtual DbSet<cPerfilRuta> cPerfilRuta { get; set; }
        public virtual DbSet<cPlaza> cPlaza { get; set; }
        public virtual DbSet<cTipoAccionRecomendacion> cTipoAccionRecomendacion { get; set; }
        public virtual DbSet<cTiposExhibicion> cTiposExhibicion { get; set; }
        public virtual DbSet<cTipoUsuario> cTipoUsuario { get; set; }
        public virtual DbSet<cTurnoRuta> cTurnoRuta { get; set; }
        public virtual DbSet<cZona> cZona { get; set; }
        public virtual DbSet<destado> destado { get; set; }
        public virtual DbSet<formatoProducto> formatoProducto { get; set; }
        public virtual DbSet<formatoTienda> formatoTienda { get; set; }
        public virtual DbSet<logError> logError { get; set; }
        public virtual DbSet<logErrorMobile> logErrorMobile { get; set; }
        public virtual DbSet<logWebService> logWebService { get; set; }
        public virtual DbSet<participacion> participacion { get; set; }
        public virtual DbSet<PlazaMunicipio> PlazaMunicipio { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<reporteIntinerarioPromotor> reporteIntinerarioPromotor { get; set; }
        public virtual DbSet<reporteTienda> reporteTienda { get; set; }
        public virtual DbSet<reporteTiendaActividadesPropias> reporteTiendaActividadesPropias { get; set; }
        public virtual DbSet<reporteTiendaDetalleCompetencia> reporteTiendaDetalleCompetencia { get; set; }
        public virtual DbSet<reporteTiendaFoto> reporteTiendaFoto { get; set; }
        public virtual DbSet<reporteTiendaIncidencia> reporteTiendaIncidencia { get; set; }
        public virtual DbSet<ReporteTiendaSegmento> ReporteTiendaSegmento { get; set; }
        public virtual DbSet<ruta> ruta { get; set; }
        public virtual DbSet<rutaIntinerario> rutaIntinerario { get; set; }
        public virtual DbSet<rutaTienda> rutaTienda { get; set; }
        public virtual DbSet<segmentoProductos> segmentoProductos { get; set; }
        public virtual DbSet<segmentos> segmentos { get; set; }
        public virtual DbSet<tienda> tienda { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuarioCliente> usuarioCliente { get; set; }
        public virtual DbSet<ZonaEstado> ZonaEstado { get; set; }
        public virtual DbSet<reporteTiendaFrentes> reporteTiendaFrentes { get; set; }
    
        [DbFunction("IntegramsaUltimateEntities", "fnctCurrentWeek")]
        public virtual IQueryable<fnctCurrentWeek_Result> fnctCurrentWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnctCurrentWeek_Result>("[IntegramsaUltimateEntities].[fnctCurrentWeek]()");
        }
    
        [DbFunction("IntegramsaUltimateEntities", "fnObtieneRutaIntinerarioSinEnviarse")]
        public virtual IQueryable<fnObtieneRutaIntinerarioSinEnviarse_Result> fnObtieneRutaIntinerarioSinEnviarse(Nullable<int> numSemana, Nullable<int> idUsuario)
        {
            var numSemanaParameter = numSemana.HasValue ?
                new ObjectParameter("numSemana", numSemana) :
                new ObjectParameter("numSemana", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnObtieneRutaIntinerarioSinEnviarse_Result>("[IntegramsaUltimateEntities].[fnObtieneRutaIntinerarioSinEnviarse](@numSemana, @idUsuario)", numSemanaParameter, idUsuarioParameter);
        }
    }
}
