//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventarios
    {
        public int idInventario { get; set; }
        public Nullable<int> idTienda { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> numSemana { get; set; }
        public Nullable<decimal> cantidadVendida { get; set; }
        public Nullable<int> idEstatusInv { get; set; }
        public string sku { get; set; }
        public string numTienda { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idCadena { get; set; }
        public Nullable<int> idCriterio { get; set; }
        public Nullable<int> idPromotor { get; set; }
        public Nullable<int> cantidadInventario { get; set; }
        public Nullable<decimal> diasInventario { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual tienda tienda { get; set; }
        public virtual inventarioEstatus inventarioEstatus { get; set; }
    }
}
