//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participacion
    {
        public int idFrente { get; set; }
        public string totalFrente { get; set; }
        public string frenteSegmento { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
