//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlazaMunicipio
    {
        public int id { get; set; }
        public Nullable<int> idPlaza { get; set; }
        public Nullable<int> idMunicipio { get; set; }
    
        public virtual cmunicipio cmunicipio { get; set; }
        public virtual cPlaza cPlaza { get; set; }
    }
}
