//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ponderacion
    {
        public int id { get; set; }
        public int idSegmento { get; set; }
        public int idCliente { get; set; }
        public Nullable<decimal> ponderacion1 { get; set; }
    }
}
