//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteTiendaActividadesPropias
    {
        public int id { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idTipoDeEshibicion { get; set; }
        public Nullable<int> idReporteTienda { get; set; }
    
        public virtual cTiposExhibicion cTiposExhibicion { get; set; }
        public virtual producto producto { get; set; }
        public virtual reporteTienda reporteTienda { get; set; }
    }
}
