//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteIntinerarioPromotor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reporteIntinerarioPromotor()
        {
            this.reporteTienda = new HashSet<reporteTienda>();
        }
    
        public int id { get; set; }
        public Nullable<int> idRutaIntinerario { get; set; }
        public Nullable<System.DateTime> fechaReporte { get; set; }
        public Nullable<int> idUsuarioPromotor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> numSemana { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> storeCheck { get; set; }
        public Nullable<int> idEncargado { get; set; }
    
        public virtual cEstado cEstado { get; set; }
        public virtual rutaIntinerario rutaIntinerario { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTienda> reporteTienda { get; set; }
    }
}
