//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteTiendaActividadesPropias
    {
        public int id { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idTipoDeEshibicion { get; set; }
        public Nullable<int> idReporteTienda { get; set; }
    
        public virtual cTiposExhibicion cTiposExhibicion { get; set; }
        public virtual producto producto { get; set; }
        public virtual reporteTienda reporteTienda { get; set; }
    }
}
