//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteTiendaIncidencia
    {
        public int id { get; set; }
        public Nullable<int> idReporteTienda { get; set; }
        public Nullable<int> idProblema { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> idAcciones { get; set; }
        public Nullable<int> idRecomendaciones { get; set; }
        public Nullable<int> idProducto { get; set; }
    
        public virtual cAccionesRecomendaciones cAccionesRecomendaciones { get; set; }
        public virtual cAccionesRecomendaciones cAccionesRecomendaciones1 { get; set; }
        public virtual cIncidenciaProblema cIncidenciaProblema { get; set; }
        public virtual producto producto { get; set; }
        public virtual reporteTienda reporteTienda { get; set; }
    }
}
