//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteTienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reporteTienda()
        {
            this.reporteTiendaActividadesPropias = new HashSet<reporteTiendaActividadesPropias>();
            this.reporteTiendaDetalleCompetencia = new HashSet<reporteTiendaDetalleCompetencia>();
            this.reporteTiendaFoto = new HashSet<reporteTiendaFoto>();
            this.reporteTiendaIncidencia = new HashSet<reporteTiendaIncidencia>();
            this.reporteTiendaFrentes = new HashSet<reporteTiendaFrentes>();
            this.ReporteTiendaSegmento = new HashSet<ReporteTiendaSegmento>();
        }
    
        public int id { get; set; }
        public Nullable<int> idRutaItinerario { get; set; }
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public string encargado { get; set; }
        public System.Data.Entity.Spatial.DbGeography ubicacion { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idUsuarioPromotor { get; set; }
        public Nullable<int> entrada { get; set; }
        public Nullable<int> saludar { get; set; }
        public Nullable<int> anaquel { get; set; }
        public Nullable<int> sacarProducto { get; set; }
        public Nullable<int> etiquetar { get; set; }
        public Nullable<int> rotarProducto { get; set; }
        public Nullable<int> ajusteInventario { get; set; }
        public Nullable<int> registroSalida { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> idReporteIntinerarioPromotor { get; set; }
    
        public virtual cEstado cEstado { get; set; }
        public virtual reporteIntinerarioPromotor reporteIntinerarioPromotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTiendaActividadesPropias> reporteTiendaActividadesPropias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTiendaDetalleCompetencia> reporteTiendaDetalleCompetencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTiendaFoto> reporteTiendaFoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTiendaIncidencia> reporteTiendaIncidencia { get; set; }
        public virtual rutaIntinerario rutaIntinerario { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTiendaFrentes> reporteTiendaFrentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteTiendaSegmento> ReporteTiendaSegmento { get; set; }
    }
}
