//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteIntinerarioPromotor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reporteIntinerarioPromotor()
        {
            this.reporteTienda = new HashSet<reporteTienda>();
        }
    
        public int id { get; set; }
        public Nullable<int> idRutaIntinerario { get; set; }
        public Nullable<System.DateTime> fechaReporte { get; set; }
        public Nullable<int> idUsuarioPromotor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> numSemana { get; set; }
        public Nullable<int> ano { get; set; }
    
        public virtual cEstado cEstado { get; set; }
        public virtual rutaIntinerario rutaIntinerario { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTienda> reporteTienda { get; set; }
    }
}
