//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteTiendaFoto
    {
        public int id { get; set; }
        public Nullable<int> idReporteTienda { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> idFotoProposito { get; set; }
        public string comentario { get; set; }
        public string url { get; set; }
    
        public virtual cFotoProposito cFotoProposito { get; set; }
        public virtual reporteTienda reporteTienda { get; set; }
    }
}
