//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporteTiendaIncidencia
    {
        public int id { get; set; }
        public Nullable<int> idReporteTienda { get; set; }
        public Nullable<int> idProblema { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> idAcciones { get; set; }
        public Nullable<int> idRecomendaciones { get; set; }
        public Nullable<int> idProducto { get; set; }
    
        public virtual cAccionesRecomendaciones cAccionesRecomendaciones { get; set; }
        public virtual cAccionesRecomendaciones cAccionesRecomendaciones1 { get; set; }
        public virtual cIncidenciaProblema cIncidenciaProblema { get; set; }
        public virtual producto producto { get; set; }
        public virtual reporteTienda reporteTienda { get; set; }
    }
}
