//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteTiendaSegmento
    {
        public Nullable<int> idreporteTienda { get; set; }
        public Nullable<int> idSegmento { get; set; }
        public Nullable<int> cantidadSegmento { get; set; }
        public int id { get; set; }
    
        public virtual reporteTienda reporteTienda { get; set; }
        public virtual segmentos segmentos { get; set; }
    }
}
