//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutaIntinerario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rutaIntinerario()
        {
            this.reporteIntinerarioPromotor = new HashSet<reporteIntinerarioPromotor>();
            this.reporteTienda = new HashSet<reporteTienda>();
        }
    
        public int id { get; set; }
        public Nullable<int> idTienda { get; set; }
        public Nullable<int> idRuta { get; set; }
        public Nullable<int> idDiaSemana { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> numSemana { get; set; }
    
        public virtual cDiaSemana cDiaSemana { get; set; }
        public virtual cEstado cEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteIntinerarioPromotor> reporteIntinerarioPromotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporteTienda> reporteTienda { get; set; }
        public virtual ruta ruta { get; set; }
        public virtual tienda tienda { get; set; }
    }
}
