//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutaTienda
    {
        public int id { get; set; }
        public Nullable<int> idTienda { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idClouster { get; set; }
        public Nullable<int> idFactorVisita { get; set; }
        public Nullable<int> idRuta { get; set; }
    
        public virtual cClouster cClouster { get; set; }
        public virtual cEstado cEstado { get; set; }
        public virtual cFactorVisita cFactorVisita { get; set; }
        public virtual ruta ruta { get; set; }
        public virtual tienda tienda { get; set; }
    }
}
