//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutaTienda
    {
        public int id { get; set; }
        public Nullable<int> idTienda { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idClouster { get; set; }
        public Nullable<int> idFactorVisita { get; set; }
        public Nullable<int> idRuta { get; set; }
    
        public virtual cClouster cClouster { get; set; }
        public virtual cEstado cEstado { get; set; }
        public virtual cFactorVisita cFactorVisita { get; set; }
        public virtual ruta ruta { get; set; }
        public virtual tienda tienda { get; set; }
    }
}
