//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tienda()
        {
            this.rutaIntinerario = new HashSet<rutaIntinerario>();
            this.rutaTienda = new HashSet<rutaTienda>();
            this.inventarios = new HashSet<inventarios>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idCadena { get; set; }
        public Nullable<int> idGiro { get; set; }
        public Nullable<int> idFormato { get; set; }
        public Nullable<int> idEstado { get; set; }
        public System.Data.Entity.Spatial.DbGeography ubicacion { get; set; }
        public Nullable<int> iddEstado { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public string colonia { get; set; }
        public string cp { get; set; }
        public Nullable<int> idPlaza { get; set; }
        public Nullable<int> idZona { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual cadena cadena { get; set; }
        public virtual cEstado cEstado { get; set; }
        public virtual cGiroComercial cGiroComercial { get; set; }
        public virtual cmunicipio cmunicipio { get; set; }
        public virtual cPlaza cPlaza { get; set; }
        public virtual cZona cZona { get; set; }
        public virtual destado destado { get; set; }
        public virtual formatoTienda formatoTienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rutaIntinerario> rutaIntinerario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rutaTienda> rutaTienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventarios> inventarios { get; set; }
    }
}
