//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcoordinador
    {
        public int idPromotor { get; set; }
        public int tipoPromotor { get; set; }
        public Nullable<int> tipoCoordinador { get; set; }
        public Nullable<int> idSupervisor { get; set; }
        public Nullable<int> idCoordinador { get; set; }
        public Nullable<int> idCliente { get; set; }
        public int id { get; set; }
        public string nombre { get; set; }
        public string materno { get; set; }
        public string paterno { get; set; }
    }
}
