//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcoordinador
    {
        public int idPromotor { get; set; }
        public int tipoPromotor { get; set; }
        public Nullable<int> tipoCoordinador { get; set; }
        public Nullable<int> idSupervisor { get; set; }
        public Nullable<int> idCoordinador { get; set; }
        public Nullable<int> idCliente { get; set; }
        public int id { get; set; }
        public string nombre { get; set; }
        public string materno { get; set; }
        public string paterno { get; set; }
    }
}
