//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInventario
    {
        public Nullable<int> numSemana { get; set; }
        public Nullable<int> idTienda { get; set; }
        public int idInventario { get; set; }
        public string Producto { get; set; }
        public string Tienda { get; set; }
        public string Status { get; set; }
        public string Criterio { get; set; }
        public Nullable<decimal> Ventas { get; set; }
        public Nullable<decimal> Días_Inv { get; set; }
        public Nullable<int> Inventario { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idCadena { get; set; }
        public Nullable<int> idCriterio { get; set; }
        public Nullable<int> idEstatusInv { get; set; }
    }
}
