//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInventario
    {
        public Nullable<int> numSemana { get; set; }
        public Nullable<int> idTienda { get; set; }
        public int idInventario { get; set; }
        public string Producto { get; set; }
        public string Tienda { get; set; }
        public string Status { get; set; }
        public string Criterio { get; set; }
        public Nullable<decimal> Ventas { get; set; }
        public Nullable<decimal> Días_Inv { get; set; }
        public Nullable<int> Inventario { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idCadena { get; set; }
        public Nullable<int> idCriterio { get; set; }
        public Nullable<int> idEstatusInv { get; set; }
    }
}
