//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwreporteEfectivadPrincipal
    {
        public Nullable<int> idCliente { get; set; }
        public string cliente { get; set; }
        public Nullable<int> idRuta { get; set; }
        public string codigoRuta { get; set; }
        public int idCoordinador { get; set; }
        public string coordinador { get; set; }
        public Nullable<int> idPromotor { get; set; }
        public string promotor { get; set; }
        public Nullable<int> idCadena { get; set; }
        public string cadena { get; set; }
        public string det { get; set; }
        public Nullable<int> idTienda { get; set; }
        public string tienda { get; set; }
    }
}
