//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwreporteTienda
    {
        public int id { get; set; }
        public Nullable<int> idRutaItinerario { get; set; }
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public string encargado { get; set; }
        public System.Data.Entity.Spatial.DbGeography ubicacion { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idUsuarioPromotor { get; set; }
        public Nullable<int> entrada { get; set; }
        public Nullable<int> saludar { get; set; }
        public Nullable<int> anaquel { get; set; }
        public Nullable<int> sacarProducto { get; set; }
        public Nullable<int> etiquetar { get; set; }
        public Nullable<int> rotarProducto { get; set; }
        public Nullable<int> ajusteInventario { get; set; }
        public Nullable<int> registroSalida { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> idReporteIntinerarioPromotor { get; set; }
        public Nullable<int> numSemana { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> idDiaSemana { get; set; }
        public Nullable<int> idTienda { get; set; }
        public Nullable<int> idCadena { get; set; }
        public string nombreTienda { get; set; }
    }
}
