//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReporteIntinerarioPromotorPlaza
    {
        public int id { get; set; }
        public Nullable<int> idRutaIntinerario { get; set; }
        public Nullable<int> idTienda { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idPlaza { get; set; }
        public string plaza { get; set; }
    }
}
