//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReporteIntinerarioPromotorPlaza
    {
        public int id { get; set; }
        public Nullable<int> idRutaIntinerario { get; set; }
        public Nullable<int> idTienda { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idPlaza { get; set; }
        public string plaza { get; set; }
    }
}
