//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReporteAsistenciaFechaEspecifica
    {
        public int id { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string PLAZA { get; set; }
        public Nullable<System.DateTime> Entrada { get; set; }
        public Nullable<System.DateTime> Salida { get; set; }
        public string tiempoEfectivo { get; set; }
        public int tiempoEfectivoMinutos { get; set; }
        public Nullable<int> tiendasVisitadas { get; set; }
        public Nullable<int> tiendasAVisitar { get; set; }
        public Nullable<int> dentroPerimetro { get; set; }
        public Nullable<int> fueraPerimetro { get; set; }
    }
}
