//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwreporteEfectivadPrincipal
    {
        public Nullable<int> idCliente { get; set; }
        public string cliente { get; set; }
        public Nullable<int> idRuta { get; set; }
        public string codigoRuta { get; set; }
        public int idCoordinador { get; set; }
        public string coordinador { get; set; }
        public Nullable<int> idPromotor { get; set; }
        public string promotor { get; set; }
        public Nullable<int> idCadena { get; set; }
        public string cadena { get; set; }
        public string det { get; set; }
        public Nullable<int> idTienda { get; set; }
        public string tienda { get; set; }
    }
}
