//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRutaIntinerario
    {
        public int id { get; set; }
        public Nullable<int> idTienda { get; set; }
        public Nullable<int> idRuta { get; set; }
        public Nullable<int> idDiaSemana { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> numSemana { get; set; }
        public string nombreTienda { get; set; }
        public Nullable<int> idCadena { get; set; }
        public System.Data.Entity.Spatial.DbGeography ubicacion { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public Nullable<int> idPlaza { get; set; }
        public string nombrePlaza { get; set; }
    }
}
