//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRutaIntinerarioSinEnviarse
    {
        public int id { get; set; }
        public Nullable<int> idTienda { get; set; }
        public Nullable<int> idRuta { get; set; }
        public Nullable<int> idDiaSemana { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> numSemana { get; set; }
        public Nullable<int> idPromotor { get; set; }
    }
}
