//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwta
    {
        public Nullable<int> rip { get; set; }
        public Nullable<int> idCliente { get; set; }
        public int idCoordinador { get; set; }
        public Nullable<int> idPromotor { get; set; }
        public Nullable<int> idTienda { get; set; }
        public int ta { get; set; }
        public Nullable<int> cob { get; set; }
        public int fp { get; set; }
        public int dp { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string fechaText { get; set; }
    }
}
