//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwta
    {
        public Nullable<int> rip { get; set; }
        public Nullable<int> idCliente { get; set; }
        public int idCoordinador { get; set; }
        public Nullable<int> idPromotor { get; set; }
        public Nullable<int> idTienda { get; set; }
        public int ta { get; set; }
        public Nullable<int> cob { get; set; }
        public int fp { get; set; }
        public int dp { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string fechaText { get; set; }
    }
}
