//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegramsaUltimate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaEstado
    {
        public int id { get; set; }
        public Nullable<int> idZona { get; set; }
        public Nullable<int> iddEstado { get; set; }
    
        public virtual cZona cZona { get; set; }
        public virtual destado destado { get; set; }
    }
}
